### ISSUE TITLE
onCloseReceived() doesnt fire

### ISSUE THREAD

**Issue by kazimad** [gusavila92/java-android-websocket-client#7]
onCloseReceived() doesnt fire

my webcocket settings 

webSocketClient?.setConnectTimeout(10000)
webSocketClient?.setReadTimeout(60000)
 webSocketClient?.connect()

maybe my problem on Timeoutsettings ?

**Comment by gusavila92** [comment]
It happens sometimes when the server doesn't send the Close frame, because not all of them implement the WebSocket protocol strictly, they have some missing features, and the Close frame is one of the most common. I think that the server is closing the TCP connection without sending a close frame first.
